import type {Metadata} from "next";
import bg from "../../public/login_bg.gif";

export const metadata: Metadata = {
    title: "clone tweeter Next App",
    description: "Generated by create next app",
};

export default function Layout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <main
            className="flex h-screen w-full flex-col items-center justify-center align-middle bg-cover bg-center"
            style={{
                backgroundImage: `url(${bg.src})`,
            }}
        >
            <div className="items-center justify-between text-sm lg:flex">{children}</div>
        </main>
    );
}

//    <div className="bg-cover bg-center" style={{backgroundImage: "url('/login_bg.gif')"}}>
