import type {Metadata} from "next";

export const metadata: Metadata = {
    title: "clone tweeter Next App",
    description: "Generated by create next app",
};

export default function Layout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <main className="flex h-screen w-full flex-col items-center justify-center align-middle">
            <div className="items-center justify-between text-sm lg:flex">{children}</div>
        </main>
    );
}
