import type {Metadata} from "next";
import localFont from "next/font/local";
import "./globals.css";

const myFont = localFont({
    src: "./fonts/DungGeunMo.ttf",
    display: "swap",
});

export const metadata: Metadata = {
    title: "clone tweeter Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning className={myFont.className}>
            <body className={`bg-black *:text-white`}>{children}</body>
        </html>
    );
}
