import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import LeftSidebar from '@/components/LeftSidebar';

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body className={inter.className + ` font-mono`}>
                <div className="flex h-screen bg-black text-white">
                    <LeftSidebar />
                    {children}
                </div>
                
                {/* <main className="flex h-screen w-full flex-col items-center justify-center align-middle">
                    <div className="items-center justify-between text-sm lg:flex">{children}</div>
                </main> */}
            </body>
        </html>
    );
}
