import type {Metadata} from "next";
import LeftSidebar from "@/components/LeftSidebar";

export const metadata: Metadata = {
    title: "clone tweeter Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <div className="flex h-screen">
            <LeftSidebar />
            {children}
        </div>
    );
}
